/**
 * Shared domain constants for the G-NAF address autocomplete system.
 *
 * Single source of truth for state codes, street-type abbreviations, and
 * flat-type prefixes used by the tokenizer, API route layer, and tests.
 * Import from here instead of declaring local copies to prevent drift.
 */

export const VALID_STATES: ReadonlySet<string> = new Set([
  "ACT",
  "NSW",
  "NT",
  "QLD",
  "SA",
  "TAS",
  "VIC",
  "WA",
  "OT",
]);

export const VALID_STATES_LC: ReadonlySet<string> = new Set(
  [...VALID_STATES].map((s) => s.toLowerCase()),
);

// Common street type suffixes (abbreviated & full) — the last token should
// never be treated as a locality when it matches one of these.
export const STREET_TYPE_LC: ReadonlySet<string> = new Set([
  "st",
  "street",
  "rd",
  "road",
  "dr",
  "drive",
  "av",
  "ave",
  "avenue",
  "ct",
  "court",
  "crt",
  "pl",
  "place",
  "ln",
  "lane",
  "cl",
  "close",
  "cr",
  "cres",
  "crescent",
  "tce",
  "terrace",
  "cct",
  "circuit",
  "pde",
  "parade",
  "gr",
  "grove",
  "bvd",
  "blvd",
  "boulevard",
  "hwy",
  "highway",
  "pkwy",
  "parkway",
  "esp",
  "esplanade",
  "tr",
  "trl",
  "trail",
  "tk",
  "track",
  "way",
  "rise",
  "row",
  "cir",
  "circle",
  "loop",
  "walk",
]);

// Maps user-typed street-type variants to their canonical abbreviations.
// Used to populate TokenizedQuery.streetTypeAbbrev (e.g. "ST,") for tier1's
// display-text boost. Comma-suffixed so it matches the formatted display.
export const STREET_TYPE_ABBREV: Record<string, string> = {
  st: "st",
  street: "st",
  rd: "rd",
  road: "rd",
  dr: "dr",
  drive: "dr",
  cl: "cl",
  close: "cl",
  ct: "ct",
  court: "ct",
  crt: "ct",
  av: "av",
  ave: "av",
  avenue: "av",
  pl: "pl",
  place: "pl",
  ln: "ln",
  lane: "ln",
  cr: "cr",
  cres: "cr",
  crescent: "cr",
  tce: "tce",
  terrace: "tce",
  cct: "cct",
  circuit: "cct",
  pde: "pde",
  parade: "pde",
  gr: "gr",
  grove: "gr",
  bvd: "bvd",
  blvd: "bvd",
  boulevard: "bvd",
  hwy: "hwy",
  highway: "hwy",
  pkwy: "pkwy",
  parkway: "pkwy",
  esp: "esp",
  esplanade: "esp",
  tr: "trl",
  trl: "trl",
  trail: "trl",
  tk: "tk",
  track: "tk",
  walk: "wk",
  cir: "cir",
  circle: "cir",
  loop: "loop",
  rise: "rise",
  row: "row",
  way: "way",
};

// G-NAF flat type codes — when the user types "unit" / "apt" / "flat" / "u",
// they're describing a flat type, not a street name.
export const FLAT_TYPE_LC: ReadonlySet<string> = new Set([
  "u",
  "unit",
  "apt",
  "apartment",
  "f",
  "flat",
  "sh",
  "shop",
  "ste",
  "suite",
  "ph",
  "penthouse",
  "th",
  "townhouse",
  "tnhs",
  "ofc",
  "office",
  "vl",
  "vlla",
  "villa",
  "rm",
  "r",
  "l",
  "level",
  "lot",
  "site",
  "carpark",
  "hse",
  "house",
  "bldg",
  "building",
  "duplex",
  "fl",
  "floor",
]);

// English ordinal suffixes used in numbered street names like "2nd AVE",
// "4th ST", "1st AVE". These are NOT street types; adding them as allowed
// trailing-letter patterns prevents isAlphanumericJunkToken from blocking
// valid ordinal street-number queries. "st" and "rd" are already covered
// by STREET_TYPE_LC.
export const ORDINAL_SUFFIX_LC: ReadonlySet<string> = new Set(["nd", "th"]);
